### ISSUE TITLE
Build fails with "android gradle plugin version 2.4.0-alpha7 is too old"

### ISSUE THREAD

**Issue by xenomachina** [yanex/anko-template-project#10] opened 2017-07-18 21:06 UTC
When I attempt to build, I get this error from Android Studio.

> Error:(1, 0) The android gradle plugin version 2.4.0-alpha7 is too old, please update to the latest version.
> 
> To override this check from the command line please set the ANDROID_DAILY_OVERRIDE environment variable to "bb224d0df16322a5c3b8930d6ae3b41476360609"

Using `gradlew` from the command line gives a similar the same error.

**Comment by yanex** [comment] 2023-11-24 14:27
The issue is closed as Anko is [deprecated](https://github.com/Kotlin/anko/blob/16ff09b952f8fb3ce2c6107caf6e788ef50ec19f/GOODBYE.md).

**Closed as completed by yanex** 2023-11-24 14:27 UTC
