### ISSUE TITLE
one error in richview.kt

### ISSUE THREAD

**Issue by hougys** [yanex/anko-template-project#16] opened 2018-02-19 10:18 UTC
in richview.kt
    private fun init() = AnkoContext.createDelegate(this).apply {
    gravity = CENTER

I need add var gravity,why?

**Comment by thoaihuynhnguyen** [comment] 2019-11-19 05:32
Error super, how to fix it?

 constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init()
    }

**Comment by yanex** [comment] 2023-11-24 14:27
The issue is closed as Anko is [deprecated](https://github.com/Kotlin/anko/blob/16ff09b952f8fb3ce2c6107caf6e788ef50ec19f/GOODBYE.md).

**Closed as completed by yanex** 2023-11-24 14:27 UTC
