### ISSUE TITLE
about a complex list viewholder

### ISSUE THREAD

**Issue by 29995270** [yanex/anko-template-project#2] opened 2015-12-18 02:07 UTC
Thanks for your example.
If my viewholder has a lot of views, how can i handle their reference.
Should i set a id in anko expression, and findViewById in viewholder?

**Comment by yanex** [comment] 2023-11-24 14:27
The issue is closed as Anko is [deprecated](https://github.com/Kotlin/anko/blob/16ff09b952f8fb3ce2c6107caf6e788ef50ec19f/GOODBYE.md).

**Closed as completed by yanex** 2023-11-24 14:27 UTC
